version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
      day: monday
    open-pull-requests-limit: 5
    groups:
      typescript-eslint:
        patterns:
          - "typescript-eslint"
          - "@typescript-eslint/*"
